# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UqJ0hqdbHo_jMqMzE3U1C-UR94aLOmW
"""

import pandas as pd
all_sheets= pd.read_excel("/content/EduPro Online Platform.xlsx",sheet_name=None)
print(all_sheets.keys())

df_users = pd.read_excel('/content/EduPro Online Platform.xlsx',sheet_name='Users')
df_teachers = pd.read_excel('/content/EduPro Online Platform.xlsx', sheet_name='Teachers')
df_courses = pd.read_excel('/content/EduPro Online Platform.xlsx',sheet_name='Courses')
df_transactions = pd.read_excel('/content/EduPro Online Platform.xlsx',sheet_name='Transactions')

import pandas as pd
from sklearn.preprocessing import StandardScaler


# Merge data to get a comprehensive view
df_full = pd.merge(df_transactions, df_users, on="UserID")

# Create features for each user: Total Enrollment count and average transaction value
features = df_full.groupby("UserID").agg({
    "CourseID": "count",
    "Amount": "mean"
}).rename(columns={"CourseID": "Enrollment_Count", "Amount": "Avg_Spend"})

# Scale the data (CRITICAL for K-Means)
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

from sklearn.cluster import KMeans

# 1. Elbow Method to find optimal 'k'
inertia = []
for k in range(1, 11):
    model = KMeans(n_clusters=k, random_state=42, n_init=10)
    model.fit(features_scaled)
    inertia.append(model.inertia_)

# 2. Assign Clusters (Assuming k=3 based on your project requirement)
final_model = KMeans(n_clusters=3, random_state=42, n_init=10)
features['Cluster'] = final_model.fit_predict(features_scaled)

import matplotlib.pyplot as plt

# 1. Visualize the clusters
plt.scatter(features_scaled[:, 0], features_scaled[:, 1], c=features['Cluster'], cmap='viridis')
plt.title("Learner Segmentation")
plt.xlabel("Enrollment Count (Scaled)")
plt.ylabel("Average Spend (Scaled)")
plt.show()

# 2. Recommendation Logic
def recommend_for_user(user_id):
    user_cluster = features.loc[user_id, 'Cluster']
    # Filter original transactions for users in the same cluster
    cluster_members = features[features['Cluster'] == user_cluster].index
    recs = df_full[df_full['UserID'].isin(cluster_members)]['CourseID'].mode()[0]
    return f"Recommended Course ID for Cluster {user_cluster}: {recs}"

# Example Usage:
# print(recommend_for_user(101))

# Create a dictionary to hold your project summary
project_summary = {
    "Project": "EduPro Personalized Recommendation System",
    "Methodology": "Unsupervised Learning (K-Means Clustering)",
    "Key_Benefit": "Improved learner retention via segment-based targeting",
    "Recommendation_Logic": "Cluster-level popularity filtering"
}

# Print the conclusion for your documentation
print("--- PROJECT CONCLUSION ---")
for key, value in project_summary.items():
    print(f"{key}: {value}")

print("\nFinal Assessment: The implementation of K-Means clustering effectively ")
print("transforms raw transaction data into actionable user segments, successfully ")
print("addressing the 'one-size-fits-all' problem in current course delivery.")





